/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hexen_software_cuelrcmaster_IMEJNI */

#ifndef _Included_com_hexen_software_cuelrcmaster_IMEJNI
#define _Included_com_hexen_software_cuelrcmaster_IMEJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hexen_software_cuelrcmaster_IMEJNI
 * Method:    KanjiToKana
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hexen_software_cuelrcmaster_IMEJNI_KanjiToKana
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
